let students=[
{"name":"高金锋",
"school":" ",
"city":"合肥",
"province":"安徽",
"major":"软件工程",
},
{"name":"张睿泽",
"school":" ",
"city":"昌平区",
"province":"北京",
"major":"理科实验班类",
},
{"name":"钟佳禹",
"school":" ",
"city":"海淀区",
"province":"北京",
"major":"经济管理",
},
{"name":"柏星佑",
"school":" ",
"city":"昌平区",
"province":"北京",
"major":"智能科学与技术",
},
{"name":"潘子乔",
"school":" ",
"city":"成都",
"province":"四川",
"major":"通信微电子",
},
{"name":"张兆文",
"school":" ",
"city":"沈阳",
"province":"辽宁",
"major":"应用物理学",
},
{"name":"方文浩",
"school":" ",
"city":"秦皇岛",
"province":"河北",
"major":"计算机科学与技术",
},
{"name":"胡馨尹",
"school":" ",
"city":"秦皇岛",
"province":"河北",
"major":"数学与应用数学",
},
{"name":"刘俊南",
"school":" ",
"city":"南京",
"province":"江苏",
"major":"None",
},
{"name":"李睿涵",
"school":" ",
"city":"杨浦区",
"province":"上海",
"major":"自然科学试验班",
},
{"name":"周皓天",
"school":" ",
"city":"合肥",
"province":"安徽",
"major":"计算机科学与技术",
},
{"name":"张凯旋",
"school":" ",
"city":"奉贤区",
"province":"上海",
"major":"材料类",
},
{"name":"柯廖莎",
"school":" ",
"city":"奉贤区",
"province":"上海",
"major":"生物工程",
},
{"name":"沈昕颐",
"school":" ",
"city":"闵行区",
"province":"上海",
"major":"地理科学（公费师范）",
},
{"name":"靳文惠",
"school":" ",
"city":"武汉",
"province":"湖北",
"major":"网络空间安全",
},
{"name":"史家业",
"school":" ",
"city":"武汉",
"province":"湖北",
"major":"计算机科学与技术",
},
{"name":"吴桐",
"school":" ",
"city":"深圳",
"province":"广东",
"major":"无（大二分流）",
},
{"name":"赵思源",
"school":" ",
"city":"南开区",
"province":"天津",
"major":"经融学类",
},
{"name":"张若妍",
"school":" ",
"city":"南开区",
"province":"天津",
"major":"信息科学与技术",
},
{"name":"黄雨涵",
"school":" ",
"city":"闵行区",
"province":"上海",
"major":"电子信息类IEEE试点班",
},
{"name":"钱朴睿",
"school":" ",
"city":"深圳",
"province":"广东",
"major":"计算机科学与技术",
},
{"name":"张雅睿",
"school":" ",
"city":"杨浦区",
"province":"上海",
"major":"工科试验班（智能交通与车辆类）",
},
{"name":"马欣怡",
"school":" ",
"city":"武汉",
"province":"湖北",
"major":"大数据应用与管理",
},
{"name":"刘继贤",
"school":" ",
"city":"西安",
"province":"陕西",
"major":"大数据应用与管理",
},
{"name":"王若希",
"school":" ",
"city":"成都",
"province":"四川",
"major":"管理科学与工程",
},
{"name":"褚佳颖",
"school":" ",
"city":"渝北区",
"province":"重庆",
"major":"社会工作",
},
{"name":"陈元中",
"school":" ",
"city":"清水湾",
"province":"香港",
"major":"工程学",
},
{"name":"江之星",
"school":" ",
"city":"湘潭",
"province":"湖南",
"major":"数学与应用数学(自动化)",
},
{"name":"桑烨",
"school":" ",
"city":"合肥",
"province":"安徽",
"major":"空间科学与技术",
},
{"name":"胡泽汉",
"school":" ",
"city":"合肥",
"province":"安徽",
"major":"电子信息类",
},
{"name":"石信元",
"school":" ",
"city":"合肥",
"province":"安徽",
"major":"生命科学",
},
{"name":"涂成浪",
"school":" ",
"city":"合肥",
"province":"安徽",
"major":"电子信息",
},
{"name":"张嘉琪",
"school":" ",
"city":"海淀区",
"province":"北京",
"major":"数学类",
},
{"name":"白博之",
"school":" ",
"city":"海淀区",
"province":"北京",
"major":"经融学类",
},
{"name":"崔瀚",
"school":" ",
"city":"海淀区",
"province":"北京",
"major":"计算机类",
},
{"name":"章孟珽",
"school":" ",
"city":"海淀区",
"province":"北京",
"major":"经济学",
},
{"name":"杜鸿雨",
"school":" ",
"city":"武汉",
"province":"湖北",
"major":"统计学",
},
{"name":"李心妍",
"school":" ",
"city":"广州",
"province":"广东",
"major":"数学类",
},
{"name":"徐希萌",
"school":" ",
"city":"海淀区",
"province":"北京",
"major":"None",
},
{"name":"张文卓",
"school":" ",
"city":"武汉",
"province":"湖北",
"major":"新闻",
},
{"name":"张博雅",
"school":" ",
"city":"朝阳区",
"province":"北京",
"major":"金融数学",
},
{"name":"陈芳菲",
"school":" ",
"city":"广州",
"province":"广东",
"major":"金融科技",
},
{"name":"张嘉涵",
"school":" ",
"city":"广州",
"province":"广东",
"major":"临床医学",
},
{"name":"韦艺",
"school":" ",
"city":"兰州",
"province":"甘肃",
"major":"物理类",
},
{"name":"韩盼午",
"school":" ",
"city":"合肥",
"province":"安徽",
"major":"韩盼午",
},

]